// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Character: typeof import('./src/components/Character.vue')['default']
    CircleYear: typeof import('./src/components/CircleYear.vue')['default']
    Countdown: typeof import('./src/components/Countdown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LineMain: typeof import('./src/components/LineMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Undefined: typeof import('./src/components/index.vue')['default']
    World: typeof import('./src/components/World.vue')['default']
  }
}
